name:                lambda-mu-mu-calculus
version:             0.1.0.0
github:              "fizruk/lambda-mu-mu-calculus"
license:             BSD3
author:              "Nikolai Kudasov"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "2020 Nikolai Kudasov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/lambda-mu-mu-calculus#readme>

ghc-options:
- -Wall
- -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- text
- attoparsec
- mtl

library:
  source-dirs: src

executables:
  lambda-mu-mu-calculus:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-mu-mu-calculus

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-mu-mu-calculus
